// Khmer translations, keyed by the exact English source string.
// Reviewed by: (pending) — adjust values freely, keys must stay identical.
window.MANTISY_KH = {
  // Navigation + header
  "Services": "សេវាកម្ម",
  "Work": "ការងារ",
  "Our mark": "សញ្ញាសម្គាល់",
  "Studio": "ស្ទូឌីយ៉ូ",
  "Start a project": "ចាប់ផ្តើមគម្រោង",
  "See selected work": "មើលការងារជ្រើសរើស",
  "Explore": "ស្វែងយល់",

  // Hero
  "Digital agency · Phnom Penh": "ភ្នាក់ងារឌីជីថល · ភ្នំពេញ",
  "We design and build": "យើងរចនា និងបង្កើត",
  "digital products for": "ផលិតផលឌីជីថលសម្រាប់",
  "restaurants.": "ភោជនីយដ្ឋាន។",
  "retailers.": "អ្នកលក់រាយ។",
  "record labels.": "ស្ទូឌីយ៉ូផលិតកម្មចម្រៀង។",
  "clinics.": "គ្លីនិក។",
  "A studio in Russey Keo, Phnom Penh. We sit with your team, learn how the work actually gets done, and ship software your customers — and your staff — can use on the first try.": "ស្ទូឌីយ៉ូមួយនៅឫស្សីកែវ ភ្នំពេញ។ យើងអង្គុយជាមួយក្រុមរបស់អ្នក ស្វែងយល់ពីរបៀបដែលការងារធ្វើឡើងពិតប្រាកដ ហើយបញ្ចេញកម្មវិធីដែលអតិថិជន និងបុគ្គលិករបស់អ្នកអាចប្រើបានតាំងពីលើកដំបូង។",
  "Founded in Phnom Penh": "បង្កើតឡើងនៅភ្នំពេញ",

  // Services section
  "What we do": "អ្វីដែលយើងធ្វើ",
  "Everything a digital product needs, under one roof.": "អ្វីៗគ្រប់យ៉ាងដែលផលិតផលឌីជីថលត្រូវការ ក្នុងកន្លែងតែមួយ។",
  "Design, build and the systems that keep a business running day to day — handled by one team in Phnom Penh, so nothing gets lost between hand-offs.": "ការរចនា ការបង្កើត និងប្រព័ន្ធដែលធ្វើឱ្យអាជីវកម្មដំណើរការរាល់ថ្ងៃ — ដោយក្រុមតែមួយនៅភ្នំពេញ ដូច្នេះគ្មានអ្វីបាត់បង់ពេលបញ្ជូនការងារបន្តទេ។",
  "UX/UI Design": "ការរចនា UX/UI",
  "Research, flows and interfaces drawn from watching real people use the thing.": "ការស្រាវជ្រាវ លំហូរការងារ និងផ្ទាំងប្រើប្រាស់ ដែលកើតចេញពីការសង្កេតមនុស្សពិតប្រើវា។",
  "Mobile Development": "ការអភិវឌ្ឍកម្មវិធីទូរស័ព្ទ",
  "iOS and Android apps built for the phones your customers actually carry.": "កម្មវិធី iOS និង Android សាងសង់សម្រាប់ទូរស័ព្ទដែលអតិថិជនរបស់អ្នកកាន់ជាក់ស្តែង។",
  "Web Development": "ការអភិវឌ្ឍវេបសាយ",
  "Marketing sites that load fast on 4G, and web apps that hold up under a full office.": "វេបសាយទីផ្សារដែលផ្ទុកលឿនលើ 4G និងកម្មវិធីវេបដែលទ្រាំបានពេលការិយាល័យទាំងមូលប្រើ។",
  "Brand Identity": "អត្តសញ្ញាណម៉ាក",
  "Names, marks and systems that read as clearly on a shopfront as on an app icon.": "ឈ្មោះ សញ្ញា និងប្រព័ន្ធដែលអានបានច្បាស់ទាំងលើផ្ទាំងហាង និងលើរូបកម្មវិធី។",
  "POS Systems": "ប្រព័ន្ធ POS",
  "Cloud point of sale that keeps taking orders when the internet drops.": "ប្រព័ន្ធគិតលុយលើ Cloud ដែលបន្តទទួលការបញ្ជាទិញ ទោះបីអ៊ីនធឺណិតដាច់។",
  "Document Management": "ការគ្រប់គ្រងឯកសារ",
  "Paperwork that stops living in drawers — searchable, permissioned, auditable.": "ឯកសារឈប់ដេកក្នុងថត — ស្វែងរកបាន កំណត់សិទ្ធិបាន ត្រួតពិនិត្យបាន។",

  // Latest project
  "Latest project": "គម្រោងថ្មីបំផុត",
  "In progress": "កំពុងដំណើរការ",
  "Marketplace platform": "វេទិកាផ្សារអនឡាញ",
  "AEON Online — one storefront for every merchant.": "AEON Online — ផ្ទាំងលក់តែមួយសម្រាប់អ្នកជំនួញទាំងអស់។",
  "AEON ran its own branches on a single-tenant system. We're opening it into a marketplace: one catalogue that carries outside merchants alongside AEON's own stores, across four connected surfaces. Two are live, two are still on the bench.": "AEON ធ្លាប់ដំណើរការសាខារបស់ខ្លួនលើប្រព័ន្ធសម្រាប់អ្នកប្រើតែមួយ។ យើងកំពុងបើកវាទៅជាផ្សារអនឡាញ៖ កាតាឡុកតែមួយដែលដាក់អ្នកជំនួញខាងក្រៅជាមួយហាងរបស់ AEON ផ្ទាល់ លើបួនផ្ទាំងភ្ជាប់គ្នា។ ពីរកំពុងដំណើរការ ពីរទៀតនៅរង់ចាំ។",
  "Live": "កំពុងដំណើរការ",
  "In build": "កំពុងសាងសង់",
  "In design": "កំពុងរចនា",
  "Shoppers": "អ្នកទិញ",
  "Customer app": "កម្មវិធីអតិថិជន",
  "Every merchant in one storefront — browse, order, track.": "អ្នកជំនួញទាំងអស់ក្នុងផ្ទាំងលក់តែមួយ — រកមើល បញ្ជាទិញ តាមដាន។",
  "Web storefront": "ផ្ទាំងលក់លើវេប",
  "The same catalogue on the web, quick on a phone browser.": "កាតាឡុកដូចគ្នានៅលើវេប លឿនលើកម្មវិធីរុករកក្នុងទូរស័ព្ទ។",
  "Shop owners": "មាស់ហាង",
  "Merchant app": "កម្មវិធីអ្នកជំនួញ",
  "Stock, pricing and orders behind the counter.": "ស្តុក ការកំណត់តម្លៃ និងការបញ្ជាទិញ នៅខាងក្រោយបញ្ជរ។",
  "Delivery riders": "អ្នកដឹកជញ្ជូន",
  "Driver app": "កម្មវិធីអ្នកដឹក",
  "Assignment, routing and proof of delivery.": "ការប្រគល់ការងារ ការកំណត់ផ្លូវ និងភស្តុតាងដឹកជញ្ជូន។",
  "AEON branches only": "សាខា AEON តែប៉ុណ្ណោះ",
  "Incoming orders": "ការបញ្ជាទិញចូល",
  "New": "ថ្មី",
  "Accept": "ទទួល",
  "Packing": "កំពុងខ្ចប់",
  "Picked up": "បានយកទៅ",
  "3 items · Toul Kork": "៣ មុខ · ទួលគោក",
  "Read the case study": "អានករណីសិក្សា",

  // Our mark
  "Four ideas, one symbol.": "បួនគំនិត សញ្ញាតែមួយ។",
  "The Mantisy mark is a signature and a promise. Every part of it stands for something we're asked to do — so we put it where clients can see what it means.": "សញ្ញា Mantisy គឺជាហត្ថលេខា និងជាការសន្យា។ គ្រប់ផ្នែករបស់វាតំណាងឱ្យអ្វីមួយដែលគេសុំឱ្យយើងធ្វើ — ដូច្នេះយើងដាក់វានៅកន្លែងដែលអតិថិជនឃើញអត្ថន័យ។",
  "Logomark · Imagotype": "សញ្ញាម៉ាក · Imagotype",
  "We Dream. We Build. We Share.": "យើងសុបិន។ យើងបង្កើត។ យើងចែករំលែក។",
  "The tick inside the mark": "សញ្ញាធីកនៅក្នុងសញ្ញាម៉ាក",
  "Checkmark": "សញ្ញាធីក",
  "The job gets done — and done completely.": "ការងារត្រូវបានធ្វើរួច — ហើយធ្វើពេញលេញ។",
  "Two arms meeting in the middle": "ដៃពីរជួបគ្នានៅកណ្តាល",
  "Handshake": "ការចាប់ដៃគ្នា",
  "The strength of the relationship we keep with clients.": "ភាពរឹងមាំនៃទំនាក់ទំនងដែលយើងរក្សាជាមួយអតិថិជន។",
  "The stroke that climbs": "បន្ទាត់ដែលឡើងខ្ពស់",
  "Growth graph": "ក្រាបកំណើន",
  "Our mission: helping a customer reach their business goal.": "បេសកកម្មរបស់យើង៖ ជួយអតិថិជនឱ្យសម្រេចគោលដៅអាជីវកម្ម។",
  "The cycle that never stops": "វដ្តដែលមិនឈប់",
  "Support": "ការគាំទ្រ",
  "We've got your back, and we cover what you need.": "យើងនៅពីក្រោយអ្នក ហើយយើងគ្របដណ្តប់អ្វីដែលអ្នកត្រូវការ។",

  // Studio / values
  "Who we are": "យើងជានរណា",
  "Four things decide how we work.": "រឿងបួនកំណត់របៀបធ្វើការរបស់យើង។",
  "Based in Russey Keo, Phnom Penh. We work the way a small team has to — honestly, in person where it helps, and with one person you can always call.": "មានទីតាំងនៅឫស្សីកែវ ភ្នំពេញ។ យើងធ្វើការតាមរបៀបដែលក្រុមតូចមួយត្រូវធ្វើ — ដោយស្មោះត្រង់ ជួបផ្ទាល់នៅពេលចាំបាច់ ហើយមានមនុស្សម្នាក់ដែលអ្នកអាចទូរស័ព្ទបានជានិច្ច។",
  "What we are hired for": "អ្វីដែលគេជួលយើងឱ្យធ្វើ",
  "Customer success": "ជោគជ័យរបស់អតិថិជន",
  "Our job is your business goal, not our deliverable. That is how we put a smile on a client's face.": "ការងាររបស់យើងគឺគោលដៅអាជីវកម្មរបស់អ្នក មិនមែនផលិតផលដែលយើងប្រគល់ទេ។ នោះជារបៀបដែលយើងធ្វើឱ្យអតិថិជនញញឹម។",
  "Moving the business on": "ជំរុញអាជីវកម្មទៅមុខ",
  "Transformation": "ការផ្លាស់ប្តូរ",
  "We keep a client's business current and move it onto the tools that are genuinely worth the change.": "យើងរក្សាអាជីវកម្មអតិថិជនឱ្យទាន់សម័យ ហើយផ្លាស់ទៅឧបករណ៍ដែលពិតជាសមនឹងការផ្លាស់ប្តូរ។",
  "Where the ideas come from": "គំនិតមកពីណា",
  "Innovation": "នវានុវត្តន៍",
  "We are dreamers. We never stop our imagination — it is what drives the creative work.": "យើងជាអ្នកសុបិន។ យើងមិនឈប់ស្រមៃ — នោះជាអ្វីដែលជំរុញការងារច្នៃប្រឌិត។",
  "The parts nobody sees": "ផ្នែកដែលគ្មានអ្នកណាឃើញ",
  "Simplicity & detail": "ភាពសាមញ្ញ និងលម្អិត",
  "We simplify complexity, then demand accuracy from ourselves in the parts nobody sees.": "យើងធ្វើឱ្យរឿងស្មុគស្មាញក្លាយជាសាមញ្ញ បន្ទាប់មកទាមទារភាពត្រឹមត្រូវពីខ្លួនយើងក្នុងផ្នែកដែលគ្មានអ្នកណាឃើញ។",
  "What we are here for": "យើងនៅទីនេះដើម្បីអ្វី",
  "Mission": "បេសកកម្ម",
  "We take on the work we believe in, build it properly, and hand over everything we learned along the way — the files, the reasoning, the training. A client should never be locked in by what they don't understand.": "យើងទទួលការងារដែលយើងជឿជាក់ បង្កើតវាឱ្យបានត្រឹមត្រូវ ហើយប្រគល់អ្វីៗដែលយើងបានរៀនតាមផ្លូវ — ឯកសារ មូលហេតុនៃការសម្រេចចិត្ត និងការបណ្តុះបណ្តាល។ អតិថិជនមិនគួរជាប់ឃុំដោយអ្វីដែលគេមិនយល់ឡើយ។",
  "Vision": "ចក្ខុវិស័យ",
  "To be the trendsetter in Cambodia's digital space.": "ក្លាយជាអ្នកកំណត់និន្នាការក្នុងវិស័យឌីជីថលនៅកម្ពុជា។",
  "Not the biggest studio — the one local teams point to when they talk about work done well. Standards set here, by people who live here.": "មិនមែនស្ទូឌីយ៉ូធំបំផុតទេ — តែជាស្ទូឌីយ៉ូដែលក្រុមក្នុងស្រុកចង្អុលបង្ហាញពេលនិយាយពីការងារធ្វើបានល្អ។ បទដ្ឋានកំណត់នៅទីនេះ ដោយមនុស្សដែលរស់នៅទីនេះ។",
  "Core values": "គុណតម្លៃស្នូល",
  "Teamwork": "ការងារជាក្រុម",
  "Great things are never done by one person.": "រឿងធំៗមិនដែលសម្រេចដោយមនុស្សតែម្នាក់ទេ។",
  "Passion": "ចំណង់ចំណូលចិត្ត",
  "To do great work is to love what you do.": "ការធ្វើការងារល្អ គឺការស្រឡាញ់អ្វីដែលអ្នកធ្វើ។",
  "Creativity": "ការច្នៃប្រឌិត",
  "Resources are limited; creativity is unlimited.": "ធនធានមានកំណត់ តែការច្នៃប្រឌិតគ្មានកំណត់។",
  "Integrity": "សុចរិតភាព",
  "Acting with solid ethics is a necessity for everyone.": "ការប្រព្រឹត្តដោយសីលធម៌រឹងមាំ ជាតម្រូវការសម្រាប់មនុស្សគ្រប់រូប។",
  "Accountability": "ការទទួលខុសត្រូវ",
  "Accepting responsibility for our actions.": "ទទួលខុសត្រូវលើអំពើរបស់ខ្លួន។",
  "Our personality": "បុគ្គលិកលក្ខណៈរបស់យើង",
  "Teamwork.": "ការងារជាក្រុម។",
  "Professionalism.": "វិជ្ជាជីវៈ។",
  "Creativeness.": "ការច្នៃប្រឌិត។",

  // Contact
  "Start a conversation": "ចាប់ផ្តើមការសន្ទនា",
  "Come and tell us what you need.": "សូមមកប្រាប់យើងពីអ្វីដែលអ្នកត្រូវការ។",
  "Big job or small, a person here reads it and replies within two working days. Prefer to talk it through? Our door in Russey Keo is open, and we speak Khmer and English.": "ការងារធំ ឬតូច មានមនុស្សនៅទីនេះអានវា ហើយឆ្លើយតបក្នុងរយៈពេលពីរថ្ងៃធ្វើការ។ ចូលចិត្តនិយាយផ្ទាល់? ទ្វាររបស់យើងនៅឫស្សីកែវបើកចំហ ហើយយើងនិយាយភាសាខ្មែរ និងអង់គ្លេស។",
  "Visit us": "មកជួបយើង",
  "Write to us": "សរសេរមកយើង",
  "Open": "ពេលបើក",
  "Mon–Fri, 09:00–18:00 ICT (UTC+7)": "ចន្ទ–សុក្រ ៩:០០–១៨:០០ ICT (UTC+7)",
  "Phnom Penh": "ភ្នំពេញ",
  "#59, Street 9M, The Park Land Condo TK,": "ផ្ទះលេខ ៥៩ ផ្លូវ 9M, The Park Land Condo TK,",
  "Sangkat Toul Sangke, Khan Russey Keo,": "សង្កាត់ទួលសង្កែ ខណ្ឌឫស្សីកែវ,",
  "Project enquiry": "សាកសួរពីគម្រោង",
  "What do you need? *": "អ្នកត្រូវការអ្វី? *",
  "POS System": "ប្រព័ន្ធ POS",
  "Something else": "រឿងផ្សេងទៀត",
  "Full name *": "ឈ្មោះពេញ *",
  "Phone": "លេខទូរស័ព្ទ",
  "(optional)": "(ស្រេចចិត្ត)",
  "Email *": "អ៊ីមែល *",
  "Tell us a little about it": "ប្រាប់យើងបន្តិចអំពីវា",
  "Send enquiry": "ផ្ញើការសាកសួរ",

  // Footer
  "A digital studio in Phnom Penh. We dream, we build, we share.": "ស្ទូឌីយ៉ូឌីជីថលនៅភ្នំពេញ។ យើងសុបិន យើងបង្កើត យើងចែករំលែក។",
  "Contact": "ទំនាក់ទំនង",
  "#59, Street 9M, Park Land Condo TK,": "ផ្ទះលេខ ៥៩ ផ្លូវ 9M, Park Land Condo TK,",
  "Khan Russey Keo, Phnom Penh": "ខណ្ឌឫស្សីកែវ ភ្នំពេញ",
  "Follow": "តាមដាន",
  "© 2026 Mantisy Inc. All rights reserved.": "© ២០២៦ Mantisy Inc. រក្សាសិទ្ធិគ្រប់បែបយ៉ាង។",
  "Phnom Penh · Cambodia": "ភ្នំពេញ · កម្ពុជា",

  // Service detail — shared labels
  "Typical engagement": "រយៈពេលធម្មតា",
  "Team": "ក្រុមការងារ",
  "Tested in": "ធ្វើតេស្តជាមួយ",
  "Platforms": "វេទិកា",
  "Handover": "ការប្រគល់",
  "Scripts": "អក្សរ",
  "Offline": "ពេលគ្មានអ៊ីនធឺណិត",
  "Access": "សិទ្ធិចូលប្រើ",
  "Khmer / EN": "ខ្មែរ / អង់គ្លេស",
  "Khmer / Latin": "ខ្មែរ / ឡាតាំង",
  "iOS / Android": "iOS / Android",
  "You own the code": "កូដជាកម្មសិទ្ធិរបស់អ្នក",
  "Keeps selling": "បន្តលក់បាន",
  "Role-based": "តាមតួនាទី",
  "2 people": "២ នាក់",
  "2–3 people": "២–៣ នាក់",
  "3–4 people": "៣–៤ នាក់",
  "2–4 months": "២–៤ ខែ",
  "2–5 months": "២–៥ ខែ",
  "3–6 months": "៣–៦ ខែ",
  "4–6 weeks": "៤–៦ សប្តាហ៍",
  "4–8 weeks": "៤–៨ សប្តាហ៍",
  "6–12 weeks": "៦–១២ សប្តាហ៍",

  // Service detail — UX/UI
  "Interfaces drawn from evidence. We watch people use what you have, find where they stall, and design the version that doesn't need explaining.": "ផ្ទាំងប្រើប្រាស់ដែលកើតចេញពីភស្តុតាង។ យើងសង្កេតមនុស្សប្រើអ្វីដែលអ្នកមាន រកកន្លែងដែលគេជាប់ ហើយរចនាជំនាន់ដែលមិនត្រូវការពន្យល់។",
  "Listen": "ស្តាប់",
  "Interviews with your staff and your customers. We sit in the shop, the office, the warehouse.": "សម្ភាសន៍ជាមួយបុគ្គលិក និងអតិថិជនរបស់អ្នក។ យើងអង្គុយក្នុងហាង ការិយាល័យ និងឃ្លាំង។",
  "Map": "គូសផែនទី",
  "Flows and structure on the wall before any pixels. Cheapest place to be wrong.": "លំហូរ និងរចនាសម្ព័ន្ធលើជញ្ជាំង មុនពេលគូសរូបណាមួយ។ ជាកន្លែងថោកបំផុតដែលអាចខុសបាន។",
  "Draw & test": "គូរ និងសាកល្បង",
  "Clickable screens in front of real users, in Khmer and in English, every second week.": "អេក្រង់ចុចបានដាក់ជូនអ្នកប្រើពិត ជាភាសាខ្មែរ និងអង់គ្លេស រៀងរាល់ពីរសប្តាហ៍។",
  "Hand over": "ប្រគល់ជូន",
  "A component library your developers can build from, plus the reasoning behind every decision.": "បណ្ណាល័យសម្ភារៈរចនាដែលអ្នកអភិវឌ្ឍន៍របស់អ្នកអាចបន្តសាងសង់ ព្រមទាំងមូលហេតុពីក្រោយរាល់ការសម្រេចចិត្ត។",
  "Talk about your product": "ពិភាក្សាពីផលិតផលរបស់អ្នក",

  // Service detail — Mobile
  "Apps for Android and iOS built for Cambodian phones and Cambodian connections — mid-range handsets, patchy signal, mobile data that costs money.": "កម្មវិធីសម្រាប់ Android និង iOS សាងសង់សម្រាប់ទូរស័ព្ទ និងបណ្តាញនៅកម្ពុជា — ទូរស័ព្ទកម្រិតមធ្យម សេវាអ៊ីនធឺណិតមិនស្ថិតស្ថេរ និងទិន្នន័យដែលត្រូវចំណាយប្រាក់។",
  "Scope": "កំណត់វិសាលភាព",
  "We agree the first release together and write down what is deliberately not in it.": "យើងព្រមព្រៀងគ្នាលើការចេញផ្សាយលើកដំបូង ហើយសរសេរទុកនូវអ្វីដែលចេតនាមិនបញ្ចូល។",
  "Build in fortnights": "សាងសង់ជារៀងរាល់ពីរសប្តាហ៍",
  "A working build on your own phone every two weeks. You use it, we adjust.": "កម្មវិធីដែលដំណើរការលើទូរស័ព្ទរបស់អ្នករៀងរាល់ពីរសប្តាហ៍។ អ្នកប្រើ យើងកែសម្រួល។",
  "Test on real devices": "សាកល្បងលើឧបករណ៍ពិត",
  "On the handsets your customers actually carry, on mobile data, not just on wifi.": "លើទូរស័ព្ទដែលអតិថិជនរបស់អ្នកកាន់ជាក់ស្តែង លើទិន្នន័យទូរស័ព្ទ មិនត្រឹមតែលើ wifi ទេ។",
  "Ship & watch": "បញ្ចេញ និងតាមដាន",
  "We publish to both stores, then stay on for the first weeks of real traffic.": "យើងបញ្ចេញលើហាងទាំងពីរ បន្ទាប់មកនៅជួយបន្តក្នុងសប្តាហ៍ដំបូងនៃការប្រើប្រាស់ពិត។",
  "Talk about your app": "ពិភាក្សាពីកម្មវិធីរបស់អ្នក",

  // Service detail — Web
  "Websites and web systems that load quickly here, are edited by your own staff, and do not need a developer for every text change.": "វេបសាយ និងប្រព័ន្ធវេបដែលផ្ទុកលឿននៅទីនេះ កែប្រែដោយបុគ្គលិករបស់អ្នកផ្ទាល់ ហើយមិនត្រូវការអ្នកអភិវឌ្ឍន៍សម្រាប់រាល់ការកែអក្សរទេ។",
  "Plan the content": "រៀបចំផែនការមាតិកា",
  "What the site must say, and who inside your team will keep it current.": "អ្វីដែលវេបសាយត្រូវបញ្ជាក់ និងអ្នកណាក្នុងក្រុមរបស់អ្នកនឹងរក្សាវាឱ្យទាន់សម័យ។",
  "Build": "សាងសង់",
  "Front end and back end together, on a staging link you can watch progress on.": "ផ្នែកខាងមុខ និងខាងក្រោយជាមួយគ្នា លើតំណសាកល្បងដែលអ្នកអាចតាមដានវឌ្ឍនភាព។",
  "Train your team": "បណ្តុះបណ្តាលក្រុមរបស់អ្នក",
  "We sit with whoever will edit it until they can do it without us.": "យើងអង្គុយជាមួយអ្នកដែលនឹងកែប្រែវា រហូតដល់គេធ្វើបានដោយគ្មានយើង។",
  "Launch & support": "ដាក់ដំណើរការ និងគាំទ្រ",
  "Go live, then a month of support while the first real visitors arrive.": "ដាក់ដំណើរការ បន្ទាប់មកគាំទ្រមួយខែ ពេលអ្នកចូលមើលពិតដំបូងមកដល់។",
  "Talk about your website": "ពិភាក្សាពីវេបសាយរបស់អ្នក",

  // Service detail — Brand
  "A mark, a type system and the rules for using them — built to work in Khmer and Latin script, in print and on a phone screen.": "សញ្ញាម៉ាក ប្រព័ន្ធអក្សរ និងបទបញ្ជាប្រើប្រាស់ — សាងសង់ឱ្យដំណើរការទាំងអក្សរខ្មែរ និងឡាតាំង ទាំងលើការបោះពុម្ព និងលើអេក្រង់ទូរស័ព្ទ។",
  "Interview": "សម្ភាសន៍",
  "We talk to the founders and the staff. The brand has to be true before it is pretty.": "យើងនិយាយជាមួយស្ថាបនិក និងបុគ្គលិក។ ម៉ាកត្រូវពិតជាមុន មុននឹងស្អាត។",
  "Three genuinely different directions, not three shades of one idea.": "បីទិសដៅខុសគ្នាពិតប្រាកដ មិនមែនបីស្រមោលនៃគំនិតតែមួយទេ។",
  "Refine": "កែលម្អ",
  "One direction taken to finished artwork, tested small, tested on signage.": "ទិសដៅមួយយកទៅធ្វើជាស្នាដៃបញ្ចប់ សាកល្បងទំហំតូច និងសាកល្បងលើផ្ទាំងសញ្ញា។",
  "Document": "កត់ត្រាជាឯកសារ",
  "A guideline book, plus every file your printer and your developers will ask for.": "សៀវភៅណែនាំ ព្រមទាំងឯកសារគ្រប់ប្រភេទដែលរោងពុម្ព និងអ្នកអភិវឌ្ឍន៍របស់អ្នកនឹងសុំ។",
  "Talk about your brand": "ពិភាក្សាពីម៉ាករបស់អ្នក",

  // Service detail — POS
  "Point of sale for shops, restaurants and pharmacies here — built so a new staff member can be serving customers on their first shift.": "ប្រព័ន្ធគិតលុយសម្រាប់ហាង ភោជនីយដ្ឋាន និងឱសថស្ថាននៅទីនេះ — សាងសង់ឱ្យបុគ្គលិកថ្មីអាចបម្រើអតិថិជនបានតាំងពីវេនដំបូង។",
  "Watch a shift": "សង្កេតវេនការងារ",
  "We stand behind the counter during a busy period before designing anything.": "យើងឈរនៅខាងក្រោយបញ្ជរក្នុងអំឡុងពេលមមាញឹក មុននឹងរចនាអ្វីមួយ។",
  "Configure": "កំណត់រចនាសម្ព័ន្ធ",
  "Your products, your prices, your receipt, your tax handling.": "ផលិតផលរបស់អ្នក តម្លៃរបស់អ្នក វិក្កយបត្ររបស់អ្នក និងការគិតពន្ធរបស់អ្នក។",
  "Pilot in one branch": "សាកល្បងនៅសាខាមួយ",
  "One location runs it live while the old system stays as a fallback.": "ទីតាំងមួយដំណើរការវាជាក់ស្តែង ចំណែកប្រព័ន្ធចាស់នៅរក្សាទុកជាជម្រើសបម្រុង។",
  "Roll out & train": "ពង្រីក និងបណ្តុះបណ្តាល",
  "Branch by branch, training each team on site as we go.": "សាខាមួយម្តងៗ បណ្តុះបណ្តាលក្រុមនីមួយៗនៅនឹងកន្លែង។",
  "Talk about your shop floor": "ពិភាក្សាពីផ្ទៃលក់របស់អ្នក",

  // Service detail — Documents
  "Approvals, records and filing moved off paper and out of shared drives — so a document can be found, and so you can see who signed it.": "ការអនុម័ត កំណត់ត្រា និងការតម្កល់ឯកសារ ផ្លាស់ចេញពីក្រដាស និងពី shared drive — ដើម្បីរកឯកសារបាន និងឃើញថាអ្នកណាបានចុះហត្ថលេខា។",
  "Trace the paper": "តាមដានក្រដាស",
  "We follow one document through your office, desk by desk, signature by signature.": "យើងតាមដានឯកសារមួយឆ្លងកាត់ការិយាល័យរបស់អ្នក តុមួយម្តងៗ ហត្ថលេខាមួយម្តងៗ។",
  "Design the flow": "រចនាលំហូរ",
  "Who submits, who approves, what happens when someone is on leave.": "អ្នកណាដាក់ស្នើ អ្នកណាអនុម័ត និងមានអ្វីកើតឡើងពេលមាននរណាម្នាក់សម្រាកការងារ។",
  "Build & migrate": "សាងសង់ និងផ្ទេរទិន្នន័យ",
  "The system, plus bringing your existing records in and organising them.": "ប្រព័ន្ធ ព្រមទាំងបញ្ចូលកំណត់ត្រាដែលមានស្រាប់ និងរៀបចំវាឱ្យមានសណ្តាប់ធ្នាប់។",
  "Train & switch": "បណ្តុះបណ្តាល និងផ្លាស់ប្តូរ",
  "Department by department, with the paper process kept until people trust it.": "ផ្នែកមួយម្តងៗ ដោយរក្សាដំណើរការក្រដាសទុក រហូតដល់មនុស្សជឿជាក់លើប្រព័ន្ធថ្មី។",
  "Talk about your paperwork": "ពិភាក្សាពីឯកសាររបស់អ្នក",

  // Service detail — section labels
  "Home": "ទំព័រដើម",
  "How the work runs": "របៀបដែលការងារដំណើរការ",
  "What you get": "អ្វីដែលអ្នកទទួលបាន",
  "Good fit if": "សមរម្យប្រសិនបើ",

  // What you get — UX/UI
  "Research findings, written plainly": "លទ្ធផលស្រាវជ្រាវ សរសេរជាភាសាងាយយល់",
  "User flows and information architecture": "លំហូរអ្នកប្រើ និងរចនាសម្ព័ន្ធព័ត៌មាន",
  "Interactive prototype, Khmer and English": "គំរូអន្តរកម្ម ជាភាសាខ្មែរ និងអង់គ្លេស",
  "Design system and component library": "ប្រព័ន្ធរចនា និងបណ្ណាល័យសម្ភារៈ",
  "Developer handover and two weeks of support": "ការប្រគល់ជូនអ្នកអភិវឌ្ឍន៍ និងការគាំទ្រពីរសប្តាហ៍",
  "People abandon your sign-up, your staff keep a paper workaround beside the software, or you're about to build something and want to be sure it's the right thing.": "មនុស្សបោះបង់ការចុះឈ្មោះរបស់អ្នក បុគ្គលិករបស់អ្នកនៅប្រើក្រដាសក្បែរកម្មវិធី ឬអ្នករៀបនឹងសាងសង់អ្វីមួយ ហើយចង់ប្រាកដថាវាត្រឹមត្រូវ។",

  // What you get — Mobile
  "Android and iOS apps from one codebase": "កម្មវិធី Android និង iOS ពីកូដតែមួយ",
  "Store listings published under your account": "ការដាក់លក់លើហាងក្រោមគណនីរបស់អ្នក",
  "Crash and error reporting you can read": "របាយការណ៍កំហុស និងការគាំងដែលអ្នកអានបាន",
  "Source code and build instructions": "កូដដើម និងការណែនាំសាងសង់",
  "Handover session with your team": "វេនប្រគល់ការងារជាមួយក្រុមរបស់អ្នក",
  "You need your service in someone’s hand rather than their browser, or your current app was built by someone you can no longer reach.": "អ្នកត្រូវការសេវារបស់អ្នកនៅក្នុងដៃគេ ជាជាងក្នុងកម្មវិធីរុករក ឬកម្មវិធីបច្ចុប្បន្នរបស់អ្នកធ្វើឡើងដោយអ្នកដែលអ្នកទាក់ទងមិនបានទៀត។",

  // What you get — Web
  "Responsive site or web system": "វេបសាយ ឬប្រព័ន្ធវេបដែលសម្របតាមអេក្រង់",
  "Content editing your staff can use": "ការកែមាតិកាដែលបុគ្គលិករបស់អ្នកប្រើបាន",
  "Khmer and English content structure": "រចនាសម្ព័ន្ធមាតិកាខ្មែរ និងអង់គ្លេស",
  "Hosting and deployment set up in your name": "ការដំឡើង hosting និងការដាក់ដំណើរការក្រោមឈ្មោះអ្នក",
  "Training session and written notes": "វេនបណ្តុះបណ្តាល និងឯកសារកត់ត្រា",
  "Your site is slow, hard to edit, or was built years ago by someone who has moved on.": "វេបសាយរបស់អ្នកដំណើរការយឺត កែពិបាក ឬធ្វើឡើងជាច្រើនឆ្នាំមុនដោយអ្នកដែលចេញទៅហើយ។",

  // What you get — Brand
  "Logo in every format and lockup": "ឡូហ្គោគ្រប់ទម្រង់ និងគ្រប់ការតម្រៀប",
  "Khmer and Latin type pairing": "ការផ្គូផ្គងអក្សរខ្មែរ និងឡាតាំង",
  "Colour system with print and screen values": "ប្រព័ន្ធពណ៌ ជាមួយតម្លៃសម្រាប់បោះពុម្ព និងអេក្រង់",
  "Brand guideline book": "សៀវភៅណែនាំម៉ាក",
  "Stationery and social templates": "សម្ភារៈការិយាល័យ និងគំរូសម្រាប់បណ្តាញសង្គម",
  "You are starting out, outgrowing a logo someone made quickly, or your materials no longer look like they come from the same company.": "អ្នកទើបចាប់ផ្តើម ឬលើសពីឡូហ្គោដែលគេធ្វើយ៉ាងប្រញាប់ ឬសម្ភារៈរបស់អ្នកមើលទៅដូចមិនមែនមកពីក្រុមហ៊ុនតែមួយទៀតទេ។",

  // What you get — POS
  "Till software for counter and tablet": "កម្មវិធីគិតលុយសម្រាប់បញ្ជរ និងថេប្លេត",
  "Stock and product management": "ការគ្រប់គ្រងស្តុក និងផលិតផល",
  "Daily takings and shift reports": "របាយការណ៍ចំណូលប្រចាំថ្ងៃ និងតាមវេន",
  "Offline mode that syncs when the connection returns": "មុខងារគ្មានអ៊ីនធឺណិត ដែលធ្វើសមកាលកម្មពេលបណ្តាញត្រឡប់មកវិញ",
  "On-site training for each branch": "ការបណ្តុះបណ្តាលនៅនឹងកន្លែងសម្រាប់សាខានីមួយៗ",
  "You are counting stock by hand, reconciling takings from paper, or running different systems in different branches.": "អ្នករាប់ស្តុកដោយដៃ ផ្ទៀងផ្ទាត់ចំណូលពីក្រដាស ឬដំណើរការប្រព័ន្ធខុសៗគ្នាតាមសាខាផ្សេងៗ។",

  // What you get — Documents
  "Document store with search": "ឃ្លាំងឯកសារជាមួយមុខងារស្វែងរក",
  "Approval routing and digital sign-off": "ការបញ្ជូនសំណើអនុម័ត និងការចុះហត្ថលេខាឌីជីថល",
  "Role-based access by department": "សិទ្ធិចូលប្រើតាមតួនាទី និងតាមផ្នែក",
  "Full history of who did what and when": "ប្រវត្តិពេញលេញថាអ្នកណាធ្វើអ្វី និងពេលណា",
  "Migration of your existing records": "ការផ្ទេរកំណត់ត្រាដែលមានស្រាប់របស់អ្នក",
  "Approvals stall on someone’s desk, records live in one person’s folder, or an audit means a week of searching.": "ការអនុម័តជាប់នៅលើតុនរណាម្នាក់ កំណត់ត្រានៅក្នុងថតរបស់មនុស្សតែម្នាក់ ឬការត្រួតពិនិត្យត្រូវចំណាយពេលមួយសប្តាហ៍ដើម្បីរក។",

  // Project detail — AEON Online
  "AEON Online": "AEON Online",
  "AEON Online: from single-tenant branches to a marketplace": "AEON Online៖ ពីសាខាប្រព័ន្ធតែមួយ ទៅជាផ្សារអនឡាញ",
  "Sector": "វិស័យ",
  "Retail & e-commerce": "ការលក់រាយ និងពាណិជ្ជកម្មអេឡិចត្រូនិក",
  "UX/UI · Web · iOS · Android": "UX/UI · វេប · iOS · Android",
  "Year": "ឆ្នាំ",
  "Delivered": "បានប្រគល់",
  "Four surfaces": "បួនផ្ទាំង",
  "One catalogue · four surfaces": "កាតាឡុកតែមួយ · បួនផ្ទាំង",
  "AEON branches": "សាខា AEON",
  "Single tenant": "ប្រព័ន្ធអ្នកប្រើតែមួយ",
  "The problem": "បញ្ហា",
  "AEON's platform served its own branches and nothing else. Multiple stores, one tenant — so there was no way to bring an outside merchant onto the same catalogue.": "វេទិកា AEON បម្រើតែសាខារបស់ខ្លួន ហើយគ្មានអ្វីផ្សេងទេ។ ហាងច្រើន តែអ្នកប្រើតែមួយ — ដូច្នេះគ្មានវិធីនាំអ្នកជំនួញខាងក្រៅចូលក្នុងកាតាឡុកតែមួយបានឡើយ។",
  "What we did": "អ្វីដែលយើងបានធ្វើ",
  "Designed and built four connected surfaces on one catalogue: shopper app, web storefront, merchant back office and driver app — every order visible to the people who act on it.": "រចនា និងសាងសង់បួនផ្ទាំងភ្ជាប់គ្នាលើកាតាឡុកតែមួយ៖ កម្មវិធីអ្នកទិញ ផ្ទាំងលក់លើវេប ប្រព័ន្ធគ្រប់គ្រងអ្នកជំនួញ និងកម្មវិធីអ្នកដឹក — រាល់ការបញ្ជាទិញមើលឃើញដោយអ្នកដែលត្រូវចាត់ចែង។",
  "Where it stands": "ស្ថានភាពបច្ចុប្បន្ន",
  "The shift": "ការផ្លាស់ប្តូរ",
  "From serving AEON’s own branches to carrying outside merchants on the same catalogue.": "ពីការបម្រើតែសាខារបស់ AEON ទៅជាការដាក់អ្នកជំនួញខាងក្រៅលើកាតាឡុកតែមួយ។",
  "← Back to all work": "← ត្រឡប់ទៅការងារទាំងអស់",
  "Start a project like this": "ចាប់ផ្តើមគម្រោងបែបនេះ"
};
